/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  t113s3Sidebar: [{type: 'autogenerated', dirName: 'T113s3-Industrial'}],
  v851seSidebar: [{type: 'autogenerated', dirName: 'TinyVision'}],
  d1hdSidebar: [{type: 'autogenerated', dirName: 'D1h-DualDisplay'}],
  /*d213dkSidebar: [{type: 'autogenerated', dirName: 'D213-DevKit'}],*/
  mp135dkSidebar: [{type: 'autogenerated', dirName: 'MP135-DevKit'}],
  d1scvbsSidebar: [{type: 'autogenerated', dirName: 'D1s-CVBS'}],
  t113iSidebar: [{type: 'autogenerated', dirName: 'T113i-Industrial'}],
  t113s3proSidebar: [{type: 'autogenerated', dirName: 'T113s3-Pro'}],
  r818dshanpirosxSidebar: [{type: 'autogenerated', dirName: 'R818-DshanPI-ROSx'}],
  h616Sidebar: [{type: 'autogenerated', dirName: 'H616-YuzukiHD-Chameleon'}],
};

export default sidebars;
